---
version: "2.1"
services:
  plex:
    image: lscr.io/linuxserver/plex:latest
    container_name: plex
    network_mode: host
    environment:
      - PUID=1001
      - PGID=1001
      - VERSION=docker
      - TZ=Asia/Kolkata
      - PLEX_CLAIM= ${PLEX_CLAIM}
    volumes:
      - /home/${DOCKER_USER}/docker/plex/config:/config
      - /home/${DOCKER_USER}/qbittorrentDownloads:/qbittorrentDownloads
    ports:
      - 32400:32400
    restart: unless-stopped
