version: "2.1"
services:
  jellyfin:
    image: lscr.io/linuxserver/jellyfin:latest
    container_name: jellyfin
    environment:
      - PUID=1001
      - PGID=1001
      - TZ=Asia/Kolkata
    volumes:
      - /home/${DOCKER_USER}/docker/jellyfin/config:/config
      - /home/${DOCKER_USER}/downloads:/data/downloads
    ports:
      - 8096:8096
    restart: unless-stopped
